name: Jobs

on:
  push:

jobs:
  concurrency-job1:
    runs-on: ubuntu-latest
    concurrency: 
      group: test
    steps:
      - run: sleep 15

  concurrency-job2:
    runs-on: ubuntu-latest
    concurrency: 
      group: test
    steps:
      - run: sleep 15
      
  deploy-job:
    name: deploy job
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: test build output
        run: echo ${{ needs.build-job.outputs.build-output }}
        
  build-job:
    outputs:
      build-output: ${{ steps.buildStep.outputs.bildOut }}
  name: build jobs
  runs-on: ubuntu-latest
  containers:
    image: oven/bun:slim
  steps:
    - name: define output variables
      id: buildsetup
      run: |
        bunver=$(bun --version)
        echo "buildOut=$bunver" >> "$GITHUB_OUTPUT"
